"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/api";
import Stat from "../../components/Stat";
import {AreaChart,Area,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from "recharts";
import {Bell,Users,AlertTriangle} from "lucide-react";
export default function Dashboard(){const[s,setS]=useState<any>(),[tr,setTr]=useState<any[]>([]),[n,setN]=useState<any[]>([]),[lb,setLb]=useState<any[]>([]);
useEffect(()=>{Promise.all([api("/api/dashboard/summary"),api("/api/dashboard/trends"),api("/api/dashboard/notifications"),api("/api/dashboard/leaderboard")]).then(([a,b,c,d])=>{setS(a);setTr(b);setN(c);setLb(d)})},[]);
if(!s)return <p className="mx-auto max-w-7xl p-10 text-slate-400">Loading command center…</p>;
return <section className="mx-auto max-w-7xl px-5 py-10"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold text-green-400">ADMIN COMMAND CENTER</p><h1 className="mt-1 text-4xl font-black">Campus Sustainability OS</h1><p className="mt-2 text-slate-400">One operational view from disposal to verified impact.</p></div><span className="rounded-xl bg-green-400/10 px-4 py-2 text-sm text-green-300">System online</span></div>
<div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Stat label="Waste Events" value={s.waste_events} note="AI-assisted"/><Stat label="E-Waste Assets" value={s.e_waste_assets} note={s.recycled_assets+" recycled"}/><Stat label="Segregation Rate" value={s.segregation_rate+"%"} note="Campus estimate"/><Stat label="Green Credits" value={s.green_credits} note="Verified actions"/></div>
<div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="card p-6"><h2 className="font-bold">Waste vs Recycling</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={tr}><XAxis dataKey="day"/><YAxis/><Tooltip/><Area type="monotone" dataKey="waste" stroke="#22c55e" fill="#22c55e" fillOpacity=".15"/><Area type="monotone" dataKey="recycled" stroke="#06b6d4" fill="#06b6d4" fillOpacity=".1"/></AreaChart></ResponsiveContainer></div></div>
<div className="card p-6"><h2 className="font-bold">Waste Composition</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={Object.entries(s.by_category).map(([category,count])=>({category,count}))}><XAxis dataKey="category"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#22c55e"/></BarChart></ResponsiveContainer></div></div></div>
<div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="card p-6"><div className="flex items-center gap-2"><Bell className="text-yellow-300"/><h2 className="font-bold">Live Alerts</h2></div><div className="mt-4 space-y-3">{n.map(x=><div className="rounded-xl border border-white/10 p-4" key={x.id}><div className="flex gap-2">{x.severity==="critical"?<AlertTriangle className="text-red-300"/>:<Bell className="text-yellow-300"/>}<div><b>{x.title}</b><p className="text-sm text-slate-400">{x.message}</p></div></div></div>)}</div></div>
<div className="card p-6"><div className="flex items-center gap-2"><Users className="text-green-400"/><h2 className="font-bold">Green Credits Leaderboard</h2></div><div className="mt-4 space-y-2">{lb.map((x,i)=><div className="flex items-center justify-between rounded-xl bg-white/[.03] p-3" key={x.name}><span><b className="mr-3 text-green-400">#{i+1}</b>{x.name}<small className="ml-2 text-slate-500">{x.department}</small></span><b>{x.credits}</b></div>)}</div></div></div>
<div className="card mt-6 p-6"><h2 className="text-xl font-bold">Operational lifecycle</h2><div className="mt-5 grid gap-3 md:grid-cols-5">{["Identify","Segregate","Collect","Recycle","Verify Impact"].map((x,i)=><div key={x} className="rounded-xl border border-white/10 p-4"><span className="text-green-400">0{i+1}</span><p className="mt-2 font-bold">{x}</p></div>)}</div></div></section>}